{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace.name }}
spec:
  {{- with .Values.ingress.routes }}
  routes:
    {{- toYaml . | nindent 4 }}
    {{- end }}