{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "golang.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  {{- with .Values.ingress.routes }}
  routes:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}