---
name: workflow staging
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs: 
  BUILD_PROJECT: 
    runs-on: self-hosted
    steps:
      - name: Checkout Code 
        if: github.event.pull_request.base.ref == 'master'
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: local build
        if: github.event.pull_request.base.ref == 'master'
        run: |
          go mod init hello-privilee
          go mod tidy
          go build

  TEST_PROJECT: 
    needs: [BUILD_PROJECT]
    runs-on: self-hosted
    steps:
      - name: Checkout Code 
        if: github.event.pull_request.base.ref == 'master'
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: local test
        if: github.event.pull_request.base.ref == 'master'
        run: go test

  TAG_IMAGE_AND_DOCKER_BUILD:
    needs: [BUILD_PROJECT, TEST_PROJECT]
    runs-on: self-hosted
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: tag version in files
        if: github.event.pull_request.base.ref == 'master'
        run: |
          sed -i "s/^\(\s*appVersion\s*:\s*\).*/\1$GITHUB_SHA/" chart/Chart.yaml
          sed -i "s/^\(\s*tag\s*:\s*\).*/\1$GITHUB_SHA/" chart/values.yaml
          sed -i "s/^\(\s*tag\s*:\s*\).*/\1$GITHUB_SHA/" chart/values_prod.yaml

      - name: Commit files
        if: github.event.pull_request.base.ref == 'master'
        run: |
          git config --global user.name "Jlacerna"
          git config --global user.email "lacernajoshua00002828@gmail.com"
          git commit chart/ -m "Bump Application container version: $GITHUB_SHA"

      - name: Push changes
        if: github.event.pull_request.base.ref == 'master'
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.PUSHONLY_TOKEN }}
# BUILD
      - name: Build Image 
        if: github.event.pull_request.base.ref == 'master'
        run: docker build -t "$(grep -A0 'repository:' chart/values.yaml | tail -n1 | awk '{ print $2}')":"$(grep -A0 'tag:' chart/values.yaml | tail -n1 | awk '{ print $2}')" -f build/docker/Dockerfile .

      - name: Push Image
        if: github.event.pull_request.base.ref == 'master'
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 790178318219.dkr.ecr.eu-central-1.amazonaws.com
          docker push "$(grep -A0 'repository:' chart/values.yaml | tail -n1 | awk '{ print $2}')":"$(grep -A0 'tag:' chart/values.yaml | tail -n1 | awk '{ print $2}')"

      - name: Clean local Image
        if: github.event.pull_request.base.ref == 'master'
        run: docker rmi -f "$(grep -A0 'repository:' chart/values.yaml | tail -n1 | awk '{ print $2}')":"$(grep -A0 'tag:' chart/values.yaml | tail -n1 | awk '{ print $2}')"
  
  DEPLOY:
    needs: [TAG_IMAGE_AND_DOCKER_BUILD, BUILD_PROJECT, TEST_PROJECT]
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'master'
      
      - name: Budget time delay
        if: github.event.pull_request.base.ref == 'master'
        run: sleep 10
      
      - name: Deploy via argocd sync
        if: github.event.pull_request.base.ref == 'master'
        run: |
          argocd app sync privilee-demo
        